swagger: '2.0'
info:
  title: My API
  description: Descrizione della mia API
  version: 1.0.0
host: localhost:8080
basePath: /api
schemes:
  - http
  - https
paths:
  /users:
    get:
      summary: Restituisce tutti gli utenti
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      summary: Crea un nuovo utente
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: Success
definitions:
  User:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string